"""
Writes js/data.js from the game's own case files and content/demo-case.json (the
mini-case, in the app's case format), so the site never drifts from the app: titles,
teasers and age notes come from the cases.

    python tools/build_data.py

Nothing that solves a case is copied: only what the app shows on its list of cases
(subtitle, teaser, content warning). The intro films' lengths are read from media/video.
"""
import io
import json
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.abspath(os.path.join(HERE, '..'))
SCENARIO = 'C:/dev/nekri-grammi/assets/scenario'
FFMPEG = 'C:/dev/nekri-grammi/node_modules/ffmpeg-static/ffmpeg.exe'

# Where each case happens (longitude, latitude), its city, and the photo on its file.
PLACES = {
    'case-01': {'lon': 33.043, 'lat': 34.672, 'city': 'Λεμεσός'},
    'case-02': {'lon': 33.095, 'lat': 34.735, 'city': 'Γερμασόγεια'},
    'case-03': {'lon': 33.637, 'lat': 34.915, 'city': 'Λάρνακα'},
    'case-04': {'lon': 33.330, 'lat': 35.160, 'city': 'Λευκωσία'},
    'case-05': {'lon': 34.075, 'lat': 34.965, 'city': 'Κάβο Γκρέκο'},
}


def seconds(path):
    p = subprocess.run([FFMPEG, '-hide_banner', '-i', path], capture_output=True, text=True, encoding='utf-8', errors='replace')
    m = re.search(r'Duration: (\d+):(\d+):([\d.]+)', p.stderr)
    return round(int(m.group(2)) * 60 + float(m.group(3)))


def main():
    cases = []
    for cid, place in PLACES.items():
        c = json.load(io.open(os.path.join(SCENARIO, f'{cid}.json'), encoding='utf-8'))
        number, _, where = c['subtitle'].partition(' — ')
        # Case 01 carries the game's own name; on the site it goes by its place.
        title = where if c['title'] == 'Νεκρή Γραμμή' else c['title']
        cw = c.get('contentWarning') or {}
        video = os.path.join(SITE, 'media', 'video', f'intro-{cid}.mp4')
        cases.append({
            'id': cid,
            'number': number.replace('Υπόθεση ', ''),
            'title': title,
            'where': where if title != where else place['city'],
            'teaser': c['teaser'],
            'minAge': cw.get('minAge'),
            'warning': cw.get('text'),
            'hours': c['timeBudgetMinutes'] // 60,
            'cover': f'media/img/cover-{cid}.jpg',
            'video': f'media/video/intro-{cid}.mp4',
            'poster': f'media/video/intro-{cid}.jpg',
            'videoSeconds': seconds(video),
            **place,
        })
    demo = json.load(io.open(os.path.join(SITE, 'content', 'demo-case.json'), encoding='utf-8'))
    demo.pop('_about', None)
    out = ('// GENERATED by tools/build_data.py from the game\'s case files and content/demo-case.json.\n'
           f'window.NG_CASES = {json.dumps(cases, ensure_ascii=False, indent=1)};\n'
           f'window.NG_DEMO = {json.dumps(demo, ensure_ascii=False, indent=1)};\n')
    io.open(os.path.join(SITE, 'js', 'data.js'), 'w', encoding='utf-8', newline='\n').write(out)
    for c in cases:
        print(c['id'], c['number'], c['title'], '|', c['where'], c['minAge'], c['videoSeconds'], 's')


if __name__ == '__main__':
    main()
