"""
Cuts the site's Picsart takes (tools/voice_script.py) into their clips, checks each
piece the way the game checks every take (Whisper hears every word, the ending
falls, the marks keep their tune), levels it, and times every word for the
transcripts on the page.

    C:/dev/tts/cb/Scripts/python.exe tools/cut_site.py <take> <mp3> [<take> <mp3> ...]

-> media/audio/<clip>.mp3 and js/timings.js (window.NG_TIMINGS: clip -> {dur, words}).
The words are the spoken form (numbers said out), each with the second it starts.
"""
import difflib
import io
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.abspath(os.path.join(HERE, '..'))
GAME = 'C:/dev/nekri-grammi'
sys.path.insert(0, os.path.join(GAME, '.preview', 'picsart'))
sys.path.insert(0, os.path.join(GAME, 'scripts'))
sys.path.insert(0, HERE)
import cut  # noqa: E402
from chirp_voice import FFMPEG, pauses, sound, transcribe  # noqa: E402
from voice_script import takes  # noqa: E402

AUDIO = os.path.join(SITE, 'media', 'audio')
TIMINGS = os.path.join(SITE, 'js', 'timings.js')


def length(path):
    p = subprocess.run([FFMPEG, '-hide_banner', '-i', path], capture_output=True, text=True, encoding='utf-8', errors='replace')
    import re
    m = re.search(r'Duration: (\d+):(\d+):([\d.]+)', p.stderr)
    return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3))


def encode(src, start, end, out):
    """One clip, with a breath of silence either side, at -16 LUFS."""
    args = [FFMPEG, '-hide_banner', '-loglevel', 'error', '-y', '-i', src, '-ss', f'{max(0, start):.3f}']
    if end is not None:
        args += ['-to', f'{end:.3f}']
    args += ['-af', 'adelay=150|150,apad=pad_dur=0.25,loudnorm=I=-16:TP=-1.5:LRA=11', '-ac', '1', '-ar', '44100',
             '-c:a', 'libmp3lame', '-b:a', '96k', out]
    subprocess.run(args, check=True)


def word_times(spoken, heard):
    """[[word, start seconds], ...] for every spoken word, lined up letter by letter."""
    words = spoken.split()
    script, starts = '', []
    for w in words:
        starts.append(len(script))
        script += sound(w)
    got, times = '', []
    for w in heard:
        f = sound(w.word)
        for k in range(len(f)):
            times.append(w.start + (w.end - w.start) * k / max(1, len(f)))
        got += f
    if not got:
        return [[w, 0.0] for w in words], 0.0
    blocks = [b for b in difflib.SequenceMatcher(None, script, got, autojunk=False).get_matching_blocks() if b.size]
    matched = sum(b.size for b in blocks) / max(1, len(script))
    out, last = [], 0.0
    for w, s in zip(words, starts):
        at = next((b.b + max(0, s - b.a) for b in blocks if b.a + b.size > s), None)
        t = times[min(at, len(times) - 1)] if at is not None else last
        t = max(t, last)
        out.append([w, round(t, 2)])
        last = t
    return out, matched


def main():
    args = sys.argv[1:]
    os.makedirs(AUDIO, exist_ok=True)
    timings = {}
    if os.path.exists(TIMINGS):
        raw = io.open(TIMINGS, encoding='utf-8').read()
        timings = json.loads(raw[raw.index('{'):raw.rindex('}') + 1])
    plan = takes()
    for take, src in zip(args[::2], args[1::2]):
        clips = [{'id': i, 'spoken': s} for i, s in plan[take]['clips']]
        print(f'== {take}: {len(clips)} clips from {os.path.basename(src)}')
        if len(clips) > 1:
            _, heard = transcribe(src, words=True)
            spans, dur = pauses(src)
            cuts, notes = cut.boundaries(clips, heard, spans, dur)
            for n in notes:
                print('  !', n)
            edges = [(0.0, None)]
            for c in cuts:
                edges[-1] = (edges[-1][0], c[0])
                edges.append((c[1], None))
        else:
            edges = [(0.0, None)]
        for clip, (a, b) in zip(clips, edges):
            out = os.path.join(AUDIO, f"{clip['id']}.mp3")
            encode(src, a, b, out)
            status, note, heard = cut.verdict(out, clip['spoken'])
            _, words = transcribe(out, words=True)
            times, matched = word_times(clip['spoken'], words)
            timings[clip['id']] = {'dur': round(length(out), 2), 'words': times}
            print(f"  {clip['id']}: {status} ({timings[clip['id']]['dur']}s, {matched:.0%} lined up) — {note}")
            if status != 'ok':
                print(f'      heard: {heard}')
    body = json.dumps(timings, ensure_ascii=False, separators=(',', ':'))
    io.open(TIMINGS, 'w', encoding='utf-8', newline='\n').write(
        '// GENERATED by tools/cut_site.py from the recordings: when each spoken word starts.\n'
        f'window.NG_TIMINGS = {body};\n')
    print(f'{len(timings)} clips timed -> js/timings.js')


if __name__ == '__main__':
    main()
